//! `assets/status.css` is produced by Tailwind (`npm run build:css`) and is gitignored.

fn main() {
    let dir = std::path::PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let css = dir.join("assets/status.css");
    if !css.is_file() {
        panic!(
            "vmux_status_bar: missing assets/status.css (generated by Tailwind).\n\
             Run: cd crates/vmux_status_bar && npm install && npm run build:css"
        );
    }
    println!("cargo:rerun-if-changed=assets/input.css");
    println!("cargo:rerun-if-changed=tailwind.config.js");
    println!("cargo:rerun-if-changed=assets/status.css");
}
