#[derive(Debug, Clone, Copy, PartialEq, Eq, rkyv::Archive, rkyv::Serialize, rkyv::Deserialize)]
pub enum CopyModeKey {
    Left,
    Right,
    Up,
    Down,
    LineStart,
    LineEnd,
    LastNonBlank,
    FirstNonBlank,
    WordForward,
    BigWordForward,
    WordBackward,
    BigWordBackward,
    WordEndForward,
    BigWordEndForward,
    WordEndBackward,
    BigWordEndBackward,
    Top,
    Bottom,
    ScreenTop,
    ScreenMiddle,
    ScreenBottom,
    PrevParagraph,
    NextParagraph,
    FindForward(char),
    FindBackward(char),
    TillForward(char),
    TillBackward(char),
    RepeatFind,
    RepeatFindReverse,
    SwapSelectionEnds,
    PageUp,
    PageDown,
    StartSelection,
    StartLineSelection,
    Copy,
    Exit,
}

#[derive(Debug, Clone, PartialEq, Eq, rkyv::Archive, rkyv::Serialize, rkyv::Deserialize)]
pub enum CommandLifecycleKind {
    Started,
    Ended { exit_code: Option<i32> },
}
