[package]
name = "vmux_daemon"
version.workspace = true
edition.workspace = true
description = "Vmux background service executable"
publish = false

[[bin]]
name = "vmux_service"
path = "src/main.rs"

[dependencies]
bevy_app = { workspace = true }
tokio = { workspace = true }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
vmux_core = { path = "../../util/vmux_core" }
vmux_service = { path = "../../feature/vmux_service" }

[lints]
workspace = true
