pub mod contract;
pub mod edit;
pub mod encoding;
pub mod explorer_model;
pub mod fold;
pub mod fold_store;
pub mod highlight;
pub mod keymap;
pub mod lsp;
pub mod markdown;
pub mod palette;
pub mod shape;

pub(crate) mod app_key;
pub(crate) mod dir;
pub(crate) mod explorer_fs;
pub(crate) mod explorer_mutation;
pub(crate) mod explorer_outline;
pub(crate) mod explorer_panel;
pub(crate) mod explorer_search;
pub(crate) mod explorer_tabs;
pub(crate) mod explorer_tree;
pub(crate) mod history;
pub(crate) mod media;
pub(crate) mod navigation;
pub(crate) mod note;
pub(crate) mod preview;
pub(crate) mod search;
pub(crate) mod status;
pub(crate) mod viewport;
pub(crate) mod wrap;

mod plugin;

pub use contract::EditorContractPlugin;
pub use explorer_panel::StackExplorerVisibility;
pub use explorer_search::GlobalSearchRequest;
pub use lsp::LspPlugin;
pub use plugin::{EditorPlugin, FileView, restore_file_view_bundle};
pub use status::FileViewModeRequest;
